### ISSUE TITLE
Tab close button with Arc Darker

### ISSUE THREAD

**Issue by malnvenshorn** [drakkar1969/Vivaldi-Arc-Theme#2]
There is a small issue with the close button of the currently active tab when using the Arc Darler Theme. Is it possible to fix this?

![Bildschirmfoto_2020-06-13_13-10-14](https://user-images.githubusercontent.com/13801805/84579629-8f2abe00-adcf-11ea-9ecf-85a1780972e6.png)

**Comment by drakkar1969** [comment]
Sorry for the inactivity the last few months. Will take a look and try to fix asap
